#!/usr/bin/env php
<?php
/**
 * masonry
 * @author    Daniel Mason <daniel.mason@thefoundry.co.uk>
 * @copyright 2015 The Foundry Visionmongers
 * @license
 * @see       https://github.com/TheFoundryVisionmongers/Masonry
 */


// Find composer autoload.
$autoloadLocations = [
    __DIR__ . '/../../../../../vendor/autoload.php',
    __DIR__ . '/../../../../vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
];

$composerLocation = null;
foreach ($autoloadLocations as $location) {
    if (is_file($location)) {
        $composerLocation = $location;
        break;
    }
}

if (!$composerLocation) {
    die('Composer autoload could not be found');
}

// Load it
require_once $composerLocation;


// Prepare the command
use Foundry\Masonry\Console\Command\Init;
use Foundry\Masonry\Console\Command\Run;
use Symfony\Component\Console\Application;

$application = new Application();
$application->addCommands([
    new Init(),
    new Run(),
]);
$application->run();
